/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/get_market_regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Market Regime */
        post: operations["get_market_regime_mcp_tools_get_market_regime_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/calculate_var": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Var */
        post: operations["calculate_var_mcp_tools_calculate_var_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/check_graham_filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Graham Filters */
        post: operations["check_graham_filters_mcp_tools_check_graham_filters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/market_data_quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Market Data Quality */
        post: operations["market_data_quality_mcp_tools_market_data_quality_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/historical_data_normalizer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Historical Data Normalizer */
        post: operations["historical_data_normalizer_mcp_tools_historical_data_normalizer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/provider_fallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Fallback */
        post: operations["provider_fallback_mcp_tools_provider_fallback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/signal_quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signal Quality */
        post: operations["signal_quality_mcp_tools_signal_quality_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/robust_backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Robust Backtest */
        post: operations["robust_backtest_mcp_tools_robust_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/portfolio_risk_manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portfolio Risk Manager */
        post: operations["portfolio_risk_manager_mcp_tools_portfolio_risk_manager_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools/trade_execution_guard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade Execution Guard */
        post: operations["trade_execution_guard_mcp_tools_trade_execution_guard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/extract_features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Features */
        post: operations["extract_features_ml_extract_features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/predict_direction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Direction */
        post: operations["predict_direction_ml_predict_direction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/predict_sarima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Sarima */
        post: operations["predict_sarima_ml_predict_sarima_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lean/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lean Backtest */
        post: operations["lean_backtest_lean_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Workflow */
        post: operations["run_workflow_workflow_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/trigger_sentiment_scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sentiment Scan */
        post: operations["trigger_sentiment_scan_ml_trigger_sentiment_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/sentiment_cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sentiment Cache */
        get: operations["get_sentiment_cache_ml_sentiment_cache_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchSymbolRequest */
        BatchSymbolRequest: {
            /** Symbols */
            symbols: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalDataNormalizerRequest */
        HistoricalDataNormalizerRequest: {
            /** Symbol */
            symbol: string;
            /** Provider */
            provider: string;
            /**
             * Market
             * @default US
             */
            market: string;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /** Raw Dataset */
            raw_dataset?: Record<string, never>[];
            /** Metadata */
            metadata?: Record<string, never>;
        };
        /** LeanRequest */
        LeanRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: Record<string, never>;
        };
        /** MarketDataQualityRequest */
        MarketDataQualityRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Provider
             * @default yahoo-chart
             */
            provider: string;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Dataset */
            dataset?: Record<string, never>[];
            /** Metadata */
            metadata?: Record<string, never>;
        };
        /** PortfolioRiskManagerRequest */
        PortfolioRiskManagerRequest: {
            /** User Id */
            user_id?: string | null;
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @default US
             */
            market: string;
            /**
             * Final Action
             * @default HOLD
             */
            final_action: string;
            /** Signal Quality */
            signal_quality?: Record<string, never>;
            /** Robust Backtest */
            robust_backtest?: Record<string, never>;
            /** Current Price */
            current_price?: number | null;
            /** Portfolio Positions */
            portfolio_positions?: Record<string, never>[] | null;
            /** Cash Balance */
            cash_balance?: number | null;
            /** Account Equity */
            account_equity?: number | null;
            /**
             * Risk Profile
             * @default balanced
             */
            risk_profile: string;
            /** Max Position Pct */
            max_position_pct?: number | null;
            /** Max Sector Pct */
            max_sector_pct?: number | null;
            /** Max Market Pct */
            max_market_pct?: number | null;
        };
        /** ProviderFallbackRequest */
        ProviderFallbackRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @default US
             */
            market: string;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /**
             * Range
             * @default 2y
             */
            range: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Required Use
             * @default ml
             */
            required_use: string;
        };
        /** RobustBacktestRequest */
        RobustBacktestRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @default US
             */
            market: string;
            /** Provider */
            provider?: string | null;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /** Normalized Dataset */
            normalized_dataset?: Record<string, never>[];
            /** Market Data Quality */
            market_data_quality?: Record<string, never>;
            /** Signal Quality */
            signal_quality?: Record<string, never>;
            /**
             * Strategy Type
             * @default buy_and_hold
             */
            strategy_type: string;
            /** Strategy Params */
            strategy_params?: Record<string, never>;
            /**
             * Initial Capital
             * @default 10000
             */
            initial_capital: number;
            /**
             * Fees
             * @default 0
             */
            fees: number;
            /**
             * Slippage
             * @default 0
             */
            slippage: number;
        };
        /** SignalQualityRequest */
        SignalQualityRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @default US
             */
            market: string;
            /** Selected Provider */
            selected_provider?: string | null;
            /** Market Data Quality */
            market_data_quality?: Record<string, never>;
            /** Technical Indicators */
            technical_indicators?: Record<string, never>;
            /** Ml Prediction */
            ml_prediction?: unknown;
            /** Risk Metrics */
            risk_metrics?: Record<string, never>;
            /** Graham Result */
            graham_result?: Record<string, never>;
            /** Sentiment Result */
            sentiment_result?: Record<string, never>;
            /**
             * Workflow Action
             * @default HOLD
             */
            workflow_action: string;
            /**
             * Workflow Confidence
             * @default 0
             */
            workflow_confidence: number;
            /** Reasons */
            reasons?: string[];
        };
        /** SymbolRequest */
        SymbolRequest: {
            /** Symbol */
            symbol: string;
        };
        /** ToolRequest */
        ToolRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Timeframe
             * @default 1D
             */
            timeframe: string;
        };
        /** TradeExecutionGuardRequest */
        TradeExecutionGuardRequest: {
            /** User Id */
            user_id?: string | null;
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @default US
             */
            market: string;
            /**
             * Side
             * @default BUY
             */
            side: string;
            /** Requested Amount */
            requested_amount?: number | null;
            /** Requested Quantity */
            requested_quantity?: number | null;
            /** Current Price */
            current_price?: number | null;
            /** Signal Quality */
            signal_quality?: Record<string, never>;
            /** Robust Backtest */
            robust_backtest?: Record<string, never>;
            /** Portfolio Risk */
            portfolio_risk?: Record<string, never>;
            /** Market Data Quality */
            market_data_quality?: Record<string, never>;
            /** Selected Provider */
            selected_provider?: string | null;
            /** Account Equity */
            account_equity?: number | null;
            /** Cash Balance */
            cash_balance?: number | null;
            /** Current Position */
            current_position?: Record<string, never> | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_market_regime_mcp_tools_get_market_regime_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_var_mcp_tools_calculate_var_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_graham_filters_mcp_tools_check_graham_filters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymbolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_data_quality_mcp_tools_market_data_quality_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarketDataQualityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_data_normalizer_mcp_tools_historical_data_normalizer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalDataNormalizerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_fallback_mcp_tools_provider_fallback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderFallbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_quality_mcp_tools_signal_quality_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalQualityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    robust_backtest_mcp_tools_robust_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobustBacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_risk_manager_mcp_tools_portfolio_risk_manager_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioRiskManagerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trade_execution_guard_mcp_tools_trade_execution_guard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeExecutionGuardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_features_ml_extract_features_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymbolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_direction_ml_predict_direction_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_sarima_ml_predict_sarima_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lean_backtest_lean_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workflow_workflow_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymbolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sentiment_scan_ml_trigger_sentiment_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSymbolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentiment_cache_ml_sentiment_cache_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
